let s:cpo_save=&cpo
set cpo&vim

runtime vimpagerrc              " Common (view) settings go into vimpagerrc

let g:netrw_dirhistmax=0        " Avoid .netrwhist creation
set dir=$HOME/.vim/tmp/swap     " Directory for temporary files

                                " vimdiff remapping
nnoremap dn ]c
nnoremap dN [c
nnoremap du :diffupdate<CR>

                                " Split management
nnoremap tH :leftabove vsplit<CR>
nnoremap tJ :rightbelow split<CR>
nnoremap tK :leftabove split<CR>
nnoremap tL :rightbelow vsplit<CR>
nnoremap th <C-W>h
nnoremap tj <C-W>j
nnoremap tk <C-W>k
nnoremap tl <C-W>l
nnoremap tx :hide<CR>

                                " Tab management
nnoremap Th :tabprevious<CR>
nnoremap Tj :tabclose<CR>
nnoremap Tk :tabnew<CR>
nnoremap Tl :tabnext<CR>

set modeline
set notimeout                   " Don't timeout on mappings
set ttimeout                    " Do timeout on terminal key codes
set timeoutlen=100              " Timeout after 100 msec

set listchars=tab:↔­,trail:·,precedes:⇐,extends:⇒
set list
set showmode
set showcmd
set showmatch
if v:version >= 703
  set relativenumber
endif
set ruler                       " Ignored because of lightline
set laststatus=2

set autoindent
set shiftwidth=4
set softtabstop=4
set expandtab
set foldnestmax=1
set foldminlines=5

set wrap
set textwidth=72                " Canonical right column
set hidden
set backspace=indent,eol,start

if exists('&colorcolumn')
    set colorcolumn=72
endif

set backupdir=$HOME/.vim/tmp/backup
set backup
set writebackup


" Directly borrowed from https://github.com/tpope/vim-sensible
set incsearch
if maparg('<C-L>', 'n') ==# ''  " Use <C-L> to clear search highlighting
  nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif

set display+=lastline
set sessionoptions-=options

if v:version > 703 || v:version == 703 && has('patch541')
  set formatoptions+=j          " Delete comment character when
                                " joining commented lines
endif


let g:proj_flags='mstvcg'       " 'Project' flags
let g:proj_file='.config/vimproject'
let g:proj_split='vs'           " Split vertically

filetype plugin indent on

" Any private customizations go into vimrc-private
if filereadable($HOME . '/.vimrc-private')
    " Kept for backward compatibility
    source $HOME/.vimrc-private
else
    runtime vimrc-private
endif

if has('python3')
  " Vdebug customizations
  let g:vdebug_options = {
  \     'watch_window_style': 'compact',
  \ }
  let g:vdebug_features = {
  \     'max_data': 1024,
  \     'max_children': 128,
  \ }
  autocmd BufNew DebuggerStack set nowrap
else
  " Skip Vdebug loading if python is not available to avoid annoying
  " messages (see https://github.com/vim-vdebug/vdebug/pull/297)
  let g:is_vdebug_loaded=1
endif

" Append the git active branch to the status line
let g:lightline = {
\     'active': {
\         'left': [ [ 'mode', 'paste' ],
\                   [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
\     },
\     'component_function': {
\         'gitbranch': 'gitbranch#name',
\     },
\ }

" CltrP customizations
let g:ctrlp_custom_ignore = '\v/(framework|cms|vendor)$'

let &cpo=s:cpo_save
unlet s:cpo_save
